site_name: Two Wheeled Lidar Robot Simulation
site_url: 'https://TheNoobInventor.github.io/twd_lidar_robot_simulation/'
use_directory_urls: False
edit_uri: ""

theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - toc.integrate
repo_url: https://github.com/TheNoobInventor/twd_lidar_robot_simulation/
repo_name: TheNoobInventor/twd_lidar_robot_simulation
plugins:
  - search:
      lang: en
