site_name: Twd Lidar Sim
site_url: ''
use_directory_urls: False
edit_uri: ""

theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
repo_url: https://github.com/example/example-repo
repo_name: example/example-repo
plugins:
  - search:
      lang: en
